# SPDX-License-Identifier: MIT
# Copyright (c) 2020-2026 Takayuki Nagata

"""Runtime math and helper routines for Hack CPU (libm2h)."""

MPY_SYMBOLS = {
    "__mspabi_mpyi",
    "__mulhi3",
}

DIV_SYMBOLS = {
    "__mspabi_divi",
    "__divhi3",
    "__mspabi_divu",
    "__udivhi3",
    "__mspabi_remi",
    "__modhi3",
    "__mspabi_remu",
    "__umodhi3",
}

EPILOG_SYMBOLS = {f"__mspabi_func_epilog_{i}" for i in range(1, 8)}

SHIFT_SYMBOLS = {
    "__m2h_rrc",
    "__m2h_rra",
}

SLL_SYMBOLS = {
    "__mspabi_slli",
    "__ashlhi3",
}


def generate_mpy_routine() -> list[str]:
    """Generate 16-bit integer multiplication routine (__mspabi_mpyi / __mulhi3)."""
    return [
        "// === Runtime Library: 16-bit Integer Multiplication ===",
        "(__mspabi_mpyi)",
        "(__mulhi3)",
        "@__M2H_LIB_RES",
        "M=0",
        "@1",
        "D=A",
        "@__M2H_LIB_MASK",
        "M=D",
        "(__M2H_MPY_LOOP)",
        "@__M2H_LIB_MASK",
        "D=M",
        "@R13",
        "D=D&M",
        "@__M2H_MPY_SKIP_ADD",
        "D;JEQ",
        "@R12",
        "D=M",
        "@__M2H_LIB_RES",
        "M=D+M",
        "(__M2H_MPY_SKIP_ADD)",
        "@R12",
        "D=M",
        "M=D+M",
        "@__M2H_LIB_MASK",
        "D=M",
        "M=D+M",
        "D=M",
        "@__M2H_MPY_LOOP",
        "D;JNE",
        "@__M2H_LIB_RES",
        "D=M",
        "@R12",
        "M=D",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "A=D",
        "0;JMP",
    ]


def generate_div_routines() -> list[str]:
    """Generate 16-bit integer division and modulo routines."""
    return [
        "// === Runtime Library: 16-bit Integer Division & Modulo ===",
        "(__m2h_udivmod)",
        "@__M2H_LIB_Q",
        "M=0",
        "@__M2H_LIB_R",
        "M=0",
        "@R13",
        "D=M",
        "@__M2H_UDIV_ZERO",
        "D;JEQ",
        "@16",
        "D=A",
        "@__M2H_LIB_CNT",
        "M=D",
        "(__M2H_UDIV_LOOP)",
        "@__M2H_LIB_R",
        "D=M",
        "M=D+M",
        "@R12",
        "D=M",
        "@__M2H_UDIV_NO_CARRY",
        "D;JGE",
        "@__M2H_LIB_R",
        "M=M+1",
        "(__M2H_UDIV_NO_CARRY)",
        "@R12",
        "D=M",
        "M=D+M",
        "@__M2H_LIB_Q",
        "D=M",
        "M=D+M",
        "@__M2H_LIB_R",
        "D=M",
        "@__M2H_UDIV_R_NEG",
        "D;JLT",
        "@R13",
        "D=M",
        "@__M2H_UDIV_SKIP_SUB",
        "D;JLT",
        "@__M2H_LIB_R",
        "D=M",
        "@R13",
        "D=D-M",
        "@__M2H_UDIV_SKIP_SUB",
        "D;JLT",
        "@__M2H_UDIV_DO_SUB",
        "0;JMP",
        "(__M2H_UDIV_R_NEG)",
        "@R13",
        "D=M",
        "@__M2H_UDIV_DO_SUB",
        "D;JGE",
        "@__M2H_LIB_R",
        "D=M",
        "@R13",
        "D=D-M",
        "@__M2H_UDIV_SKIP_SUB",
        "D;JLT",
        "(__M2H_UDIV_DO_SUB)",
        "@R13",
        "D=M",
        "@__M2H_LIB_R",
        "M=M-D",
        "@__M2H_LIB_Q",
        "M=M+1",
        "(__M2H_UDIV_SKIP_SUB)",
        "@__M2H_LIB_CNT",
        "M=M-1",
        "D=M",
        "@__M2H_UDIV_LOOP",
        "D;JNE",
        "(__M2H_UDIV_ZERO)",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "A=D",
        "0;JMP",
        "",
        "(__mspabi_divu)",
        "(__udivhi3)",
        "@__M2H_DIVU_RET",
        "D=A",
        "@SP",
        "M=M-1",
        "A=M",
        "M=D",
        "@__m2h_udivmod",
        "0;JMP",
        "(__M2H_DIVU_RET)",
        "@__M2H_LIB_Q",
        "D=M",
        "@R12",
        "M=D",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "A=D",
        "0;JMP",
        "",
        "(__mspabi_remu)",
        "(__umodhi3)",
        "@__M2H_REMU_RET",
        "D=A",
        "@SP",
        "M=M-1",
        "A=M",
        "M=D",
        "@__m2h_udivmod",
        "0;JMP",
        "(__M2H_REMU_RET)",
        "@__M2H_LIB_R",
        "D=M",
        "@R12",
        "M=D",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "A=D",
        "0;JMP",
        "",
        "(__mspabi_divi)",
        "(__divhi3)",
        "@__M2H_LIB_SGN_Q",
        "M=0",
        "@R12",
        "D=M",
        "@__M2H_DIVI_CHK_D",
        "D;JGE",
        "@R12",
        "M=-M",
        "@__M2H_LIB_SGN_Q",
        "M=!M",
        "(__M2H_DIVI_CHK_D)",
        "@R13",
        "D=M",
        "@__M2H_DIVI_CALL",
        "D;JGE",
        "@R13",
        "M=-M",
        "@__M2H_LIB_SGN_Q",
        "M=!M",
        "(__M2H_DIVI_CALL)",
        "@__M2H_DIVI_RET",
        "D=A",
        "@SP",
        "M=M-1",
        "A=M",
        "M=D",
        "@__m2h_udivmod",
        "0;JMP",
        "(__M2H_DIVI_RET)",
        "@__M2H_LIB_SGN_Q",
        "D=M",
        "@__M2H_DIVI_POS",
        "D;JEQ",
        "@__M2H_LIB_Q",
        "D=M",
        "D=-D",
        "@R12",
        "M=D",
        "@__M2H_DIVI_END",
        "0;JMP",
        "(__M2H_DIVI_POS)",
        "@__M2H_LIB_Q",
        "D=M",
        "@R12",
        "M=D",
        "(__M2H_DIVI_END)",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "A=D",
        "0;JMP",
        "",
        "(__mspabi_remi)",
        "(__modhi3)",
        "@__M2H_LIB_SGN_R",
        "M=0",
        "@R12",
        "D=M",
        "@__M2H_REMI_CHK_D",
        "D;JGE",
        "@R12",
        "M=-M",
        "@__M2H_LIB_SGN_R",
        "M=1",
        "(__M2H_REMI_CHK_D)",
        "@R13",
        "D=M",
        "@__M2H_REMI_CALL",
        "D;JGE",
        "@R13",
        "M=-M",
        "(__M2H_REMI_CALL)",
        "@__M2H_REMI_RET",
        "D=A",
        "@SP",
        "M=M-1",
        "A=M",
        "M=D",
        "@__m2h_udivmod",
        "0;JMP",
        "(__M2H_REMI_RET)",
        "@__M2H_LIB_SGN_R",
        "D=M",
        "@__M2H_REMI_POS",
        "D;JEQ",
        "@__M2H_LIB_R",
        "D=M",
        "D=-D",
        "@R12",
        "M=D",
        "@__M2H_REMI_END",
        "0;JMP",
        "(__M2H_REMI_POS)",
        "@__M2H_LIB_R",
        "D=M",
        "@R12",
        "M=D",
        "(__M2H_REMI_END)",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "A=D",
        "0;JMP",
    ]


def generate_epilog_routines() -> list[str]:
    """Generate function epilogue helper routines for callee-saved registers."""
    return [
        "// === Runtime Library: Function Epilogue Helpers ===",
        "(__mspabi_func_epilog_7)",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "@R4",
        "M=D",
        "(__mspabi_func_epilog_6)",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "@R5",
        "M=D",
        "(__mspabi_func_epilog_5)",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "@R6",
        "M=D",
        "(__mspabi_func_epilog_4)",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "@R7",
        "M=D",
        "(__mspabi_func_epilog_3)",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "@R8",
        "M=D",
        "(__mspabi_func_epilog_2)",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "@R9",
        "M=D",
        "(__mspabi_func_epilog_1)",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "@R10",
        "M=D",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "A=D",
        "0;JMP",
    ]


def generate_shift_routines() -> list[str]:
    """Generate 1-bit right shift helper routines (rrc and rra)."""
    return [
        "// === Runtime Library: Right Shift Helpers ===",
        "(__m2h_rrc)",
        "@__M2H_LIB_RES",
        "M=0",
        "@1",
        "D=A",
        "@__M2H_LIB_DMASK",
        "M=D",
        "@2",
        "D=A",
        "@__M2H_LIB_SMASK",
        "M=D",
        "(__M2H_RRC_LOOP)",
        "@__M2H_LIB_SMASK",
        "D=M",
        "@__M2H_LIB_IN",
        "D=D&M",
        "@__M2H_RRC_SKIP",
        "D;JEQ",
        "@__M2H_LIB_DMASK",
        "D=M",
        "@__M2H_LIB_RES",
        "M=D+M",
        "(__M2H_RRC_SKIP)",
        "@__M2H_LIB_DMASK",
        "D=M",
        "M=D+M",
        "@__M2H_LIB_SMASK",
        "D=M",
        "M=D+M",
        "D=M",
        "@__M2H_RRC_LOOP",
        "D;JNE",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "A=D",
        "0;JMP",
        "",
        "(__m2h_rra)",
        "@__M2H_LIB_RES",
        "M=0",
        "@1",
        "D=A",
        "@__M2H_LIB_DMASK",
        "M=D",
        "@2",
        "D=A",
        "@__M2H_LIB_SMASK",
        "M=D",
        "(__M2H_RRA_LOOP)",
        "@__M2H_LIB_SMASK",
        "D=M",
        "@__M2H_LIB_IN",
        "D=D&M",
        "@__M2H_RRA_SKIP",
        "D;JEQ",
        "@__M2H_LIB_DMASK",
        "D=M",
        "@__M2H_LIB_RES",
        "M=D+M",
        "(__M2H_RRA_SKIP)",
        "@__M2H_LIB_DMASK",
        "D=M",
        "M=D+M",
        "@__M2H_LIB_SMASK",
        "D=M",
        "M=D+M",
        "D=M",
        "@__M2H_RRA_LOOP",
        "D;JNE",
        "@__M2H_LIB_IN",
        "D=M",
        "@__M2H_RRA_END",
        "D;JGE",
        "@32767",
        "D=A",
        "D=!D",
        "@__M2H_LIB_RES",
        "M=D|M",
        "(__M2H_RRA_END)",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "A=D",
        "0;JMP",
    ]


def generate_sll_routine() -> list[str]:
    """Generate 16-bit logical shift left helper (__mspabi_slli / __ashlhi3)."""
    return [
        "// === Runtime Library: Logical Shift Left (__mspabi_slli) ===",
        "(__mspabi_slli)",
        "(__ashlhi3)",
        "@R13",
        "D=M",
        "@__M2H_SLL_END",
        "D;JLE",
        "(__M2H_SLL_LOOP)",
        "@R12",
        "D=M",
        "M=D+M",
        "@R13",
        "M=M-1",
        "D=M",
        "@__M2H_SLL_LOOP",
        "D;JGT",
        "(__M2H_SLL_END)",
        "@SP",
        "A=M",
        "D=M",
        "@SP",
        "M=M+1",
        "A=D",
        "0;JMP",
    ]


def get_required_runtime_routines(symbols_used: set[str]) -> list[str]:
    """Return required runtime routines based on referenced symbols."""
    lines: list[str] = []
    if any(sym in symbols_used for sym in MPY_SYMBOLS):
        lines.extend(generate_mpy_routine())
        lines.append("")
    if any(sym in symbols_used for sym in DIV_SYMBOLS):
        lines.extend(generate_div_routines())
        lines.append("")
    if any(sym in symbols_used for sym in EPILOG_SYMBOLS):
        lines.extend(generate_epilog_routines())
        lines.append("")
    if any(sym in symbols_used for sym in SHIFT_SYMBOLS):
        lines.extend(generate_shift_routines())
        lines.append("")
    if any(sym in symbols_used for sym in SLL_SYMBOLS):
        lines.extend(generate_sll_routine())
        lines.append("")
    return lines
